#myarch31

spacing = 1
padding = 0
separator = " "
key_color = "#ED8796"
separator_color = "#999999"

[palette]
type = "Light"
glyph = "[#]"
spacing = 2
visible = true

[bar]
glyph = "●"
symbol_open = '('
symbol_close = ')'
visible = false
hide_delimiters = true

[box]
title = "myarch31"
border = "double"
visible = true

[box.inner_margin]
x = 2
y = 1

[custom_ascii]
color = "#ED8796"
path = "~/.config/macchina/ascii_art/big_linux"

[randomize]
key_color = false
separator_color = false
pool = "base"

[keys]
host = "Host"
kernel = "Kernel"
battery = "Battery"
os = "OS"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = "Uptime"
memory = "Memory"
machine = "Machine"
resolution = "Resolution"
cpu = "CPU"
